vich_uploader:
  db_driver: orm
  mappings:
    item_files:
      uri_prefix: '%app.path.item_files%'
      upload_destination: '%kernel.project_dir%/public%app.path.item_files%'
      directory_namer: item_files.directory_namer